### ISSUE TITLE
spectron can't start app which include module 'babel-polyfill'

### ISSUE THREAD

**Issue by mario8x** [electron/spectron#61]
I tried to start an application which included module 'babel-polyfill'. Sometimes, it can not load module 'babel-polyfill'. It happened about 3/5 times when i try to run my test script. 

Please take a look at my script: 
[](https://gist.github.com/mario8x/88e6fd73c7924f2ef31002c992a3db13)

![babel-polyfill-issue](https://cloud.githubusercontent.com/assets/5043859/15821339/64ac8032-2c19-11e6-8919-cf410c4c459a.png)

**Comment by mario8x** [comment]
I'm not sure the root cause from node js module. But when i updated my node js module from 6.2.0 to 6.2.1 then it run more stable. now the issue happens 1/10 times.

**Comment by mario8x** [comment]
Tips: to by pass this issue you just need to call restart application function.

**Comment by zeke** [comment]
@mario8x I'm not sure exactly what "call restart application function" means, but if you think this could be helped with some documentation so others don't run into the same issue, please submit a pull request.

**Comment by mario8x** [comment]
@zeke I hope this scrip help you: 
await app.start()
    //Display main process log
    const logs = await app.client.getMainProcessLogs()
    for (const log of logs) {
      if (log.includes('Cannot find module')) {
        return app.restart()
      }
    }
